/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsFrase.java
 *
 * Created on 03/07/2011, 18:19:17
 */
package br.com.bdanillomaciel.alphaenglish.forms;

import br.com.danillomaciel.alphaenglish.modelo.Frase;
import br.com.danillomaciel.alphaenglish.persistencia.FraseDao;
import br.com.danillomaciel.alphaenglish.visao.MP3;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Danillo
 */
public class ConsFrase extends javax.swing.JInternalFrame {

    /** Creates new form ConsFrase */
    public ConsFrase() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtUnidLivro = new javax.swing.JTextField();
        txtNomeLivro = new javax.swing.JTextField();
        lblNomeLivro1 = new javax.swing.JLabel();
        lblNomeLivro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtFrasePt = new javax.swing.JTextField();
        txtFraseEn = new javax.swing.JTextField();
        lblPt = new javax.swing.JLabel();
        lblEn = new javax.swing.JLabel();
        btnTocar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnRndFrase = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        radEn = new javax.swing.JRadioButton();
        radPt = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtUnidLivro.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtNomeLivro.setFont(new java.awt.Font("Tahoma", 0, 14));

        lblNomeLivro1.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblNomeLivro1.setText("Nome da lição ou unidade:");

        lblNomeLivro.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblNomeLivro.setText("Nome do livro:");

        txtFrasePt.setEditable(false);
        txtFrasePt.setFont(new java.awt.Font("Tahoma", 0, 20));
        txtFrasePt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFrasePtActionPerformed(evt);
            }
        });

        txtFraseEn.setEditable(false);
        txtFraseEn.setFont(new java.awt.Font("Tahoma", 0, 20));
        txtFraseEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFraseEnActionPerformed(evt);
            }
        });

        lblPt.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblPt.setText("Frase em Português:");

        lblEn.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblEn.setText("Frase em Inglês:");

        btnTocar.setText("Tocar");
        btnTocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTocarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPt)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblEn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFraseEn, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                            .addComponent(txtFrasePt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnTocar)))
                .addGap(140, 140, 140))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblPt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTocar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(txtFrasePt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(lblEn)
                .addGap(14, 14, 14)
                .addComponent(txtFraseEn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtFraseEn, txtFrasePt});

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnRndFrase.setText("Sortear Frase");
        btnRndFrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRndFraseActionPerformed(evt);
            }
        });

        btnVisualizar.setText("Ver Resposta");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnRndFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRndFrase, btnSair, btnVisualizar});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnRndFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnRndFrase, btnSair, btnVisualizar});

        radEn.setSelected(true);
        radEn.setText("Inglês");
        radEn.setFocusable(false);

        radPt.setText("Português");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomeLivro1)
                                    .addComponent(lblNomeLivro))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUnidLivro)
                                    .addComponent(txtNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radPt)
                                    .addComponent(radEn))
                                .addGap(56, 56, 56)))))
                .addContainerGap(48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeLivro)
                    .addComponent(txtNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radEn))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeLivro1)
                    .addComponent(txtUnidLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radPt))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFrasePtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFrasePtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFrasePtActionPerformed

    private void txtFraseEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFraseEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFraseEnActionPerformed

    private void btnRndFraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRndFraseActionPerformed
        try {
            trataRadio();
            limparTxt();
            executeRnd();
        } catch (Exception ex) {
            Logger.getLogger(ConsFrase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRndFraseActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        visOnPt();
        visOnEn();
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnTocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTocarActionPerformed
   
       tocar(trataNome());
    }//GEN-LAST:event_btnTocarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRndFrase;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTocar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblEn;
    private javax.swing.JLabel lblNomeLivro;
    private javax.swing.JLabel lblNomeLivro1;
    private javax.swing.JLabel lblPt;
    private javax.swing.JRadioButton radEn;
    private javax.swing.JRadioButton radPt;
    private javax.swing.JTextField txtFraseEn;
    private javax.swing.JTextField txtFrasePt;
    private javax.swing.JTextField txtNomeLivro;
    private javax.swing.JTextField txtUnidLivro;
    // End of variables declaration//GEN-END:variables

    public void executeRnd() throws Exception {
        FraseDao fd = new FraseDao();
        String nome, livro;
        nome = txtNomeLivro.getText();
        livro = txtUnidLivro.getText();



        Frase f = fd.buscaporRnd(nome, livro);
        txtFrasePt.setText(f.getfPortugues());
        txtFraseEn.setText(f.getfIngles());
    }

    public void limparTxt() {
        txtFrasePt.setText("");
        txtFraseEn.setText("");
    }

    public void visOnEn() {
        txtFraseEn.setVisible(true);
    }

    public void visOffEn() {
        txtFraseEn.setVisible(false);
    }

    public void trataRadio() {
        if ((radEn.isSelected() && radPt.isSelected()) || (!radEn.isSelected() && !radPt.isSelected())) {
            visOnPt();
            visOnEn();
        } else if (radEn.isSelected()) {
            radPt.setSelected(false);
            visOffPt();
            visOnEn();
        } else if (radPt.isSelected()) {
            radEn.setSelected(false);
            visOffEn();
            visOnPt();

        }
    }

    private void visOffPt() {
        txtFrasePt.setVisible(false);
    }

    private void visOnPt() {
        txtFrasePt.setVisible(true);
    }

    public void tocar(String nome) {

        String path = "E:/Meus Documentos/Meus Arquivos/projetoNetbeans/aplhaenglish/musica/" + nome + ".mp3";

        //Instanciação de um objeto File com o arquivo MP3
        File mp3File = new File(path);

        //Instanciação do Objeto MP3, a qual criamos a classe.
        MP3 musica = new MP3(mp3File);

        //Finalmente a chamada do método que toca a música
        musica.play();
    }

    private String trataNome() {
        String frase = txtFraseEn.getText();
        String s = null;
        s = frase.substring(frase.length() - 1, frase.length());
        if (s.equals("?") || s.equals(".") || s.equals("!")) {
            frase = frase.substring(0, frase.length() - 1);
        }
        return frase;
    }
 

}
